# Generated by Django 4.2.9 on 2024-02-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_clientid"),
        ("classwork", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="citation_style",
            field=models.CharField(choices=[], default="APA", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="subject",
            field=models.CharField(choices=[], default="Politics", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="type_of_work",
            field=models.CharField(choices=[], default="Essay", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_order",
                to="users.profile",
            ),
        ),
    ]
