# Generated by Django 4.2.9 on 2024-02-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0002_order_citation_style_order_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="citation_style",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="type_of_work",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Addon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("addon", models.CharField(max_length=100)),
                ("selected", models.BooleanField(default=False)),
                ("price", models.FloatField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="order_addon", to="classwork.order"
                    ),
                ),
            ],
        ),
    ]
