# Generated by Django 4.2.9 on 2024-02-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0003_alter_order_citation_style_alter_order_subject_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Citation",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="TypeOfWork",
        ),
        migrations.AlterField(
            model_name="addon",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="order_addon", to="classwork.order"
            ),
        ),
        migrations.AlterField(
            model_name="addon",
            name="price",
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="service",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="type_of_work",
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
