# Generated by Django 4.2.9 on 2024-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0004_delete_citation_delete_subject_delete_typeofwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("citation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="type_of_work",
        ),
        migrations.AddField(
            model_name="order",
            name="type_of_work",
            field=models.CharField(default="edditing", max_length=100),
            preserve_default=False,
        ),
    ]
