# Generated by Django 5.0.1 on 2024-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0005_citation_subject_remove_order_type_of_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOfWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
    ]
