# Generated by Django 5.0.1 on 2024-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0006_typeofwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type_of_work",
            field=models.CharField(default="Meal", max_length=100),
        ),
    ]
