# Generated by Django 5.0.1 on 2024-02-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0009_remove_addon_order_order_addons"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="references",
            field=models.IntegerField(default=0),
        ),
    ]
