# Generated by Django 5.0.1 on 2024-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0010_order_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderId",
            field=models.CharField(default="kjkks", max_length=20),
            preserve_default=False,
        ),
    ]
