# Generated by Django 5.0.1 on 2024-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0011_order_orderid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderId",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
