# Generated by Django 5.0.1 on 2024-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0012_alter_order_orderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
