# Generated by Django 5.0.1 on 2024-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0013_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="price",
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="pages_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="word_count",
            field=models.IntegerField(default=275),
        ),
    ]
