# Generated by Django 5.0.1 on 2024-02-09 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0014_alter_addon_price_alter_order_pages_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 2, 9, 9, 50, 52, 124590, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]
