# Generated by Django 5.0.1 on 2024-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0015_order_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
    ]
