# Generated by Django 5.0.1 on 2024-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0016_order_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pages_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
