# Generated by Django 5.0.1 on 2024-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classwork", "0017_alter_order_pages_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
