# Generated by Django 5.0.1 on 2024-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
