# Generated by Django 5.0.1 on 2024-02-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0002_orderitem_is_paid"),
        ("users", "0004_alter_profile_clientid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_type", models.CharField(max_length=100)),
                ("nature", models.CharField(max_length=100)),
                ("channel", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="client_profile", to="users.profile"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="payments.orderitem"
                    ),
                ),
            ],
        ),
    ]
