# Generated by Django 5.0.1 on 2024-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_rename_order_id_complaint_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="status",
            field=models.CharField(choices=[("O", "Open"), ("C", "Closed")], default="O", max_length=1),
        ),
    ]
