# Generated by Django 5.0.1 on 2024-02-15 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_alter_profile_clientid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("client", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.profile")),
            ],
        ),
    ]
