# Generated by Django 4.2.10 on 2024-02-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deposit",
            options={"get_latest_by": "timestamp"},
        ),
    ]
