# Generated by Django 4.2.10 on 2024-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_deposit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
