# Generated by Django 5.0.1 on 2024-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_clientid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="clientId",
            field=models.CharField(blank=True, max_length=109, null=True, unique=True),
        ),
    ]
